# Copyright (c) 2021-2024 Tigera, Inc. All rights reserved.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
ARG UBI_IMAGE

FROM registry.access.redhat.com/ubi8/ubi-minimal:8.10 as ubi

RUN microdnf upgrade


FROM scratch

# Because we build our binary with CGO, we need to add the necessary *.so files for dynamic linking.
# If *.so files are missing, you will see an error saying that your entrypoint cannot be found.
# The necessary files can be found using the ldd command on the binary.
COPY --from=ubi /lib64/ld-linux-x86-64.so.2 /lib64/ld-linux-x86-64.so.2
COPY --from=ubi /lib64/libc.so.6 /lib64/libc.so.6
COPY --from=ubi /lib64/libpthread.so.0 /lib64/libpthread.so.0

# Copy hostname configuration files from UBI so glibc hostname lookups work.
COPY --from=ubi /lib64/libnss_dns.so.2 /lib64/libnss_dns.so.2
COPY --from=ubi /lib64/libresolv.so.2 /lib64/libresolv.so.2
COPY --from=ubi /lib64/libnss_files.so.2 /lib64/libnss_files.so.2
COPY --from=ubi /etc/nsswitch.conf /etc/nsswitch.conf
COPY --from=ubi /etc/networks /etc/networks
COPY --from=ubi /etc/hosts /etc/hosts
COPY --from=ubi /etc/host.conf /etc/host.conf

COPY bin/key-cert-provisioner-amd64 /usr/bin/key-cert-provisioner

USER 10001:10001

ENTRYPOINT ["/usr/bin/key-cert-provisioner"]
